#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Write content-addressed build identity; does not compile or run the game."""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile


def git(root: Path, *arguments: str) -> str:
    result = subprocess.run(["git", "-C", str(root), *arguments], check=True,
                            capture_output=True, text=True)
    return result.stdout.strip()


def replace_changed(path: Path, data: bytes) -> None:
    if path.is_file() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(data)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--nxdk", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    root = args.root.resolve()
    dirty = bool(git(root, "status", "--porcelain", "--untracked-files=normal"))
    revision = git(root, "rev-parse", "HEAD")
    sdk_revision = git(args.nxdk, "rev-parse", "HEAD")
    manifest = {
        "source_revision": revision, "source_dirty": dirty, "nxdk_revision": sdk_revision,
        "profile": "engine-bootstrap", "build_verified": False, "boot_verified": False,
        "runtime_renderer": "unimplemented", "audio": "null",
        "network": "native-transport-source-unverified",
        "source_manifest_sha256": hashlib.sha256((root / "xbox/game/sources.mk").read_bytes()).hexdigest(),
        "profile_sha256": hashlib.sha256((root / "xbox/game/profile.h").read_bytes()).hexdigest(),
    }
    # JSON string escaping is valid for these hexadecimal Git identifiers.
    header = ("/* Generated by game_identity.py; do not edit. */\n"
              "#ifndef DP_XBOX_BUILD_IDENTITY_H\n#define DP_XBOX_BUILD_IDENTITY_H\n"
              f"#define DP_XBOX_SOURCE_REVISION {json.dumps(revision)}\n"
              f"#define DP_XBOX_SOURCE_DIRTY {int(dirty)}\n"
              f"#define DP_XBOX_NXDK_REVISION {json.dumps(sdk_revision)}\n"
              f"#define VCREVISION {revision}\n"
              "#define BUILDTYPE xbox_engine_bootstrap\n"
              "#define NO_BUILD_TIMESTAMPS 1\n#endif\n")
    replace_changed(args.output / "xbox_build_identity.h", header.encode())
    replace_changed(args.output / "build-identity.json",
                    (json.dumps(manifest, sort_keys=True, indent=2) + "\n").encode())


if __name__ == "__main__":
    main()
