#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Stage the verified Nexuiz 2.5.2 data tree for the Xbox release candidate."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import shutil
import stat
import sys
import zipfile

import build_lowmem_texture_pack
import release_inputs

CHUNK = 1024 * 1024
MAX_ENTRIES = 100_000
MAX_FILE_BYTES = 2 * 1024 * 1024 * 1024
MAX_TOTAL_BYTES = 4 * 1024 * 1024 * 1024

# One alias owns the playlist so initial zero-action startup and deliberate
# Start-to-resume use exactly the same ordered demo set.
XBOX_DEFAULTS = """// Generated by tools/xbox/stage_classic_release.py.
// Keep automatic quality disabled unless the user explicitly enables it.
joy_enable 1
joy_deadzoneforward 0.20
joy_deadzoneside 0.20
joy_deadzonepitch 0.20
joy_deadzoneyaw 0.20
joy_sensitivityforward -1
joy_sensitivityside 1
joy_sensitivitypitch 1.4
joy_sensitivityyaw -1.4
bind JOY1 +jump
bind JOY2 +crouch
bind JOY3 dropweapon
bind JOY4 weaplast
bind JOY5 weapprev
bind JOY6 weapnext
bind JOY7 +hook
bind JOY8 +zoom
bind AUX1 +attack2
bind AUX2 +attack
bind AUX3 +showscores
bind AUX4 +show_info
bind AUX5 weapprev
bind AUX6 weapnext
vid_vsync 0
cl_minfps 0
cl_minfps_force 0
cl_minfps_qualitymin 1
cl_minfps_qualitymax 1
developer_loading 1
developer_texturelogging 1
// Suspected pbGL client-array corruption produced vertical green output on NV2A.
// Use the engine's equivalent immediate path while isolating array submission.
gl_mesh_testmanualfeeding 1
// Persist pbGL-reported errors in boot-trace.txt during renderer bring-up.
gl_paranoid 1
xbox_apply_memory_profile
alias xbox_demo_start "startdemos demos/bench1 demos/demo1 demos/demo2 demos/demo3 demos/demo4 demos/demo5 demos/piece-o-cake"
xbox_demo_start
"""
AUTOEXEC_LINE = "exec xbox-defaults.cfg"
LOWMEM_PACK_NAME = "zzzz-xbox-lowmem.pk3"
LOWMEM_MAX_DIMENSION = build_lowmem_texture_pack.STOCK_MAX_DIMENSION


class StageError(ValueError):
    """The release archive cannot be staged safely and reproducibly."""


def _safe_archive_name(raw: str) -> str:
    if not raw or "\\" in raw or "\x00" in raw:
        raise StageError(f"unsafe archive path: {raw!r}")
    clean = raw[:-1] if raw.endswith("/") else raw
    if not clean:
        raise StageError("empty archive path")
    path = PurePosixPath(clean)
    if path.is_absolute() or any(part in ("", ".", "..") for part in path.parts):
        raise StageError(f"unsafe archive path: {raw!r}")
    if any(":" in part for part in path.parts):
        raise StageError(f"unsafe archive path: {raw!r}")
    return path.as_posix() + ("/" if raw.endswith("/") else "")


def _archive_entries(zf: zipfile.ZipFile) -> list[tuple[zipfile.ZipInfo, str]]:
    infos = zf.infolist()
    if not infos or len(infos) > MAX_ENTRIES:
        raise StageError("archive entry count is empty or exceeds the release limit")
    seen: set[str] = set()
    total = 0
    result: list[tuple[zipfile.ZipInfo, str]] = []
    for info in infos:
        name = _safe_archive_name(info.filename)
        folded = name.rstrip("/").casefold()
        if folded in seen:
            raise StageError(f"archive case/duplicate collision: {name}")
        seen.add(folded)
        if info.flag_bits & 1 or info.compress_type not in (zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED):
            raise StageError(f"unsupported archive entry: {name}")
        if not info.is_dir():
            if info.file_size < 0 or info.file_size > MAX_FILE_BYTES:
                raise StageError(f"archive file exceeds size limit: {name}")
            total += info.file_size
            if total > MAX_TOTAL_BYTES:
                raise StageError("archive extracted data exceeds release limit")
        result.append((info, name))
    return result


def _data_prefix(entries: list[tuple[zipfile.ZipInfo, str]]) -> str:
    candidates: set[str] = set()
    for info, name in entries:
        if info.is_dir() or not name.casefold().endswith(".pk3"):
            continue
        path = PurePosixPath(name)
        if path.parent.name.casefold() == "data":
            candidates.add(path.parent.as_posix() + "/")
    if len(candidates) != 1:
        raise StageError(
            "expected exactly one Nexuiz data directory containing PK3 files; found "
            + str(len(candidates))
        )
    return next(iter(candidates))


def _copy_member(zf: zipfile.ZipFile, info: zipfile.ZipInfo, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    with zf.open(info, "r") as source, target.open("wb") as out:
        while block := source.read(CHUNK):
            written += len(block)
            if written > info.file_size:
                raise StageError(f"archive size changed while reading: {info.filename}")
            out.write(block)
    if written != info.file_size:
        raise StageError(f"archive size mismatch: {info.filename}")


def _sha256(path: Path) -> str:
    result = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(CHUNK):
            result.update(block)
    return result.hexdigest()


def _write_xbox_defaults(data_dir: Path) -> None:
    (data_dir / "xbox-defaults.cfg").write_text(XBOX_DEFAULTS, encoding="utf-8", newline="\n")
    autoexec = data_dir / "autoexec.cfg"
    existing = autoexec.read_text(encoding="utf-8", errors="strict") if autoexec.exists() else ""
    lines = [line.strip().casefold() for line in existing.splitlines()]
    if AUTOEXEC_LINE.casefold() not in lines:
        if existing and not existing.endswith("\n"):
            existing += "\n"
        existing += AUTOEXEC_LINE + "\n"
        autoexec.write_text(existing, encoding="utf-8", newline="\n")


def stage_release(archive: Path, disc: Path, expected_sha256: str) -> dict:
    archive = archive.resolve()
    disc = disc.resolve()
    try:
        release_inputs.verify_file(archive, expected_sha256)
    except release_inputs.ReleaseInputError as exc:
        raise StageError(str(exc)) from exc

    data_dir = disc / "data"
    if data_dir.exists():
        shutil.rmtree(data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    identity_path = disc / "CONTENT-IDENTITY.json"
    if identity_path.exists():
        identity_path.unlink()

    try:
        with zipfile.ZipFile(archive, "r") as zf:
            entries = _archive_entries(zf)
            prefix = _data_prefix(entries)
            prefix_fold = prefix.casefold()
            staged_source = 0
            for info, name in entries:
                if info.is_dir() or not name.casefold().startswith(prefix_fold):
                    continue
                if stat.S_ISLNK(info.external_attr >> 16):
                    raise StageError(f"archive symlink is not supported: {name}")
                relative = name[len(prefix):]
                if not relative:
                    continue
                relpath = PurePosixPath(relative)
                if any(part in ("", ".", "..") for part in relpath.parts):
                    raise StageError(f"unsafe staged path: {relative!r}")
                target = data_dir.joinpath(*relpath.parts)
                _copy_member(zf, info, target)
                staged_source += 1
    except (OSError, zipfile.BadZipFile, UnicodeError) as exc:
        raise StageError(f"cannot stage Nexuiz archive: {exc}") from exc

    if staged_source == 0 or not any(data_dir.glob("*.pk3")):
        raise StageError("Nexuiz data directory did not stage any PK3 files")

    try:
        _write_xbox_defaults(data_dir)
    except (OSError, UnicodeError) as exc:
        raise StageError(f"cannot write Xbox defaults: {exc}") from exc

    lowmem_pack = data_dir / LOWMEM_PACK_NAME
    source_packs = sorted(
        (path for path in data_dir.glob("*.pk3") if path.name != LOWMEM_PACK_NAME),
        key=lambda path: path.name.casefold(),
    )
    try:
        lowmem_manifest = build_lowmem_texture_pack.build_pack(
            source_packs, lowmem_pack, LOWMEM_MAX_DIMENSION
        )
    except build_lowmem_texture_pack.TexturePackError as exc:
        raise StageError(f"cannot generate low-memory texture pack: {exc}") from exc

    files = []
    total = 0
    for path in sorted(p for p in data_dir.rglob("*") if p.is_file()):
        relative = path.relative_to(disc).as_posix()
        size = path.stat().st_size
        total += size
        files.append({"path": relative, "bytes": size, "sha256": _sha256(path)})

    identity = {
        "schema_version": 2,
        "release": "nexuiz-xbox-2.5.2",
        "source_file": archive.name,
        "source_sha256": release_inputs.file_sha256(archive),
        "data_prefix": prefix,
        "source_file_count": staged_source,
        "staged_file_count": len(files),
        "staged_bytes": total,
        "derived_content": {
            "path": f"data/{LOWMEM_PACK_NAME}",
            "profile": lowmem_manifest["profile"],
            "max_dimension": lowmem_manifest["max_dimension"],
            "external_lightmap_dimension": lowmem_manifest["external_lightmap_dimension"],
            "filter": lowmem_manifest["filter"],
            "entry_storage": lowmem_manifest["entry_storage"],
            "asset_count": lowmem_manifest["asset_count"],
            "bytes": lowmem_pack.stat().st_size,
            "sha256": _sha256(lowmem_pack),
        },
        "files": files,
    }
    identity_path.write_text(
        json.dumps(identity, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    return identity


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--disc", type=Path, required=True)
    parser.add_argument(
        "--lock",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "xbox" / "release" / "release-inputs.json",
    )
    args = parser.parse_args(argv)
    try:
        lock = release_inputs.load_lock(args.lock)
        identity = stage_release(args.archive, args.disc, lock["content"]["sha256"])
    except (release_inputs.ReleaseInputError, StageError) as exc:
        print(f"release staging error: {exc}", file=sys.stderr)
        return 2
    print(
        f"staged {identity['staged_file_count']} files / {identity['staged_bytes']} bytes "
        f"from {identity['source_sha256']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
