#ifndef XBOX_CLASSIC_GL_BOOTSTRAP_H
#define XBOX_CLASSIC_GL_BOOTSTRAP_H

enum
{
	XBOX_GL_BOOTSTRAP_OK = 0,
	XBOX_GL_BOOTSTRAP_PBGL_FAILED = -1,
	XBOX_GL_BOOTSTRAP_RESOLVE_FAILED = -2,
	XBOX_GL_BOOTSTRAP_IDENTITY_FAILED = -3
};

int Xbox_GLBootstrap(int pbgl_result);

#endif
